version: 1.0.{build}
image: Visual Studio 2017
environment:
  key_secret:
    secure: uwCoaeMGJZXnRF8zTkLxwWzvrLGcwwEy4Dg6mIQ/rVA=
  key_cert:
    secure: M/xtoKu3JQ6a7Trvqv2m0w==
install:
- cmd: >-
    nuget install secure-file -ExcludeVersion
    secure-file\tools\secure-file -decrypt smith_MM_certificate.pfx.enc -secret %key_secret%
build:
  verbosity: minimal
after_build:
- cmd: '"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe" sign /f "smith_MM_certificate.pfx" /p %key_cert% "ConsoleApp1\bin\Debug\netcoreapp2.0\ConsoleApp1.dll"'
artifacts:
- path: ConsoleApp1\bin\Debug\netcoreapp2.0\ConsoleApp1.dll
  name: My.dll
