TaskType = "Search"

[SearchParameters]
DisposeOfFileWhenDone = true
AddCompIons = false
DoParsimony = false
ModPeptidesAreUnique = true
NoOneHitWonders = false
MatchBetweenRuns = false
QuantifyPpmTol = 5.0
DoHistogramAnalysis = false
SearchTarget = false
DecoyType = "Reverse"
MassDiffAcceptorType = "Exact"
WritePrunedDatabase = false
KeepAllUniprotMods = true
DoLocalizationAnalysis = true
DoQuantification = false
SearchType = "Classic"
MaxFragmentSize = 30000.0
HistogramBinTolInDaltons = 0.003

[SearchParameters.ModsToWriteSelection]
ProteinTermMod = 3
UniProt = 2

[CommonParameters]
MaxParallelFilesToAnalyze = 1
MaxThreadsToUsePerFile = 7
LocalizeAll = true
ListOfModsFixed = "Common Fixed\tCarbamidomethyl of C"
ListOfModsVariable = "Common Variable\tOxidation of M"
DoPrecursorDeconvolution = false
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 3.0
DeconvolutionMaxAssumedChargeState = 12
DeconvolutionMassTolerance = "±4.0000 PPM"
TotalPartitions = 1
BIons = true
YIons = true
ZdotIons = false
CIons = false
ProductMassTolerance = "±25.0000 PPM"
PrecursorMassTolerance = "±15.0000 PPM"
ConserveMemory = true
ScoreCutoff = 5.0
ReportAllAmbiguity = true
ExcelCompatible = true
TopNpeaks = 200
MinRatio = 0.01
TrimMs1Peaks = false
TrimMsMsPeaks = true
TaskDescriptor = "SearchTask"
CalculateEValue = false

[CommonParameters.DigestionParams]
MaxMissedCleavages = 2
InitiatorMethionineBehavior = "Variable"
MinPeptideLength = 6
MaxModificationIsoforms = 4096
MaxModsForPeptide = 3
Protease = "trypsin"
SemiProteaseDigestion = false
TerminusTypeSemiProtease = "None"
